version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - .tmp/db:/var/lib/mysql
  web:
    build: backend/
    command: bash -c "rm -f tmp/pids/server && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build: frontend/
    tty: true
    ports:
      - "8000:3000"
    command: yarn dev
    volumes:
      - ./frontend:/myapp